name: "Create and push tag"
description: "Create a tag and push it"

inputs:
  token:
    description: "A GitHub token for creating a tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
          token: "${{ inputs.TOKEN }}"
          fetch-depth: 0

    - name: Fetch all tags
      # GitHub's checkout action doesn't properly fetch the current tag
      run: git fetch --tags --prune --force
      shell: bash

    - name: Set up git
      run:  |
        git config --global user.email "imagebuilder-bots+imagebuilder-bot@redhat.com"
        git config --global user.name "imagebuilder-bot"
      shell: bash

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ghapi

    - name: Create tag
      run: ${{ github.action_path }}/release.py --token "${{ inputs.TOKEN }}" --no-interactive
      shell: bash