name: "Create and push tag"
description: "Create a tag and push it"

inputs:
  token:
    description: "A GitHub token for creating a tag"
    required: true
  component:
    description: "The name of the repository triggering this action"
  username:
    description: "A GitHub user name"
    required: true
  email:
    description: "The GitHub user's email address"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
          token: "${{ inputs.TOKEN }}"
          fetch-depth: 0

    - name: Set up git
      run:  |
        git clone https://"${{ inputs.TOKEN }}"@github.com/osbuild/"${{ inputs.COMPONENT }}"
        git config --global user.email "${{ inputs.EMAIL }}"
        git config --global user.name "${{ inputs.USERNAME }}"
        git remote -v
    # GitHub's checkout action doesn't properly fetch the current tag
    #    git fetch --tags --prune --force
      shell: bash

    - name: Install Python and depends
      run: |
        sudo apt install python3
        pip install ghapi
      shell: bash

    - name: Create and push tag
      run: |
        cd ${{ github.action_path }}/"${{ inputs.COMPONENT }}"/
        ${{ github.action_path }}/release.py --user "${{ inputs.USERNAME }}" --token "${{ inputs.TOKEN }}"
      shell: bash